# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aa\Desktop\Hyper-Heuristique-for-Credit-Scoring\Interface\interface.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 600))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(960, 0, 238, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Strategie = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Strategie.setContentsMargins(0, 0, 0, 0)
        self.Strategie.setObjectName("Strategie")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.Strategie.addWidget(self.label_10)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.prob_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_i.setObjectName("prob_i")
        self.gridLayout.addWidget(self.prob_i, 1, 3, 1, 1)
        self.prob_c = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_c.setObjectName("prob_c")
        self.gridLayout.addWidget(self.prob_c, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.prob_o = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_o.setObjectName("prob_o")
        self.gridLayout.addWidget(self.prob_o, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.prob_m = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_m.setObjectName("prob_m")
        self.gridLayout.addWidget(self.prob_m, 1, 2, 1, 1)
        self.Strategie.addLayout(self.gridLayout)
        self.add_strategy = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.add_strategy.setObjectName("add_strategy")
        self.Strategie.addWidget(self.add_strategy)
        self.strategies = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.strategies.setObjectName("strategies")
        self.strategies.setColumnCount(0)
        self.strategies.setRowCount(0)
        self.Strategie.addWidget(self.strategies)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.Strategie.addWidget(self.label_15)
        self.training_model = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.training_model.setObjectName("training_model")
        self.Strategie.addWidget(self.training_model)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.Strategie.addWidget(self.label_19)
        self.treshold_type = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.treshold_type.setObjectName("treshold_type")
        self.Strategie.addWidget(self.treshold_type)
        self.seuil = QtWidgets.QWidget(self.centralwidget)
        self.seuil.setEnabled(True)
        self.seuil.setGeometry(QtCore.QRect(990, 450, 191, 101))
        self.seuil.setObjectName("seuil")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.seuil)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 191, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.panel = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.panel.setContentsMargins(0, 0, 0, 0)
        self.panel.setObjectName("panel")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.panel.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.nb_iteration_tresholding = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nb_iteration_tresholding.setObjectName("nb_iteration_tresholding")
        self.panel.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nb_iteration_tresholding)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 9, 211, 541))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Parametres = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Parametres.setContentsMargins(0, 0, 0, 0)
        self.Parametres.setObjectName("Parametres")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.prob_supp = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.prob_supp.setObjectName("prob_supp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prob_supp)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.max_attribute = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.max_attribute.setObjectName("max_attribute")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_attribute)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.max_population = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.max_population.setObjectName("max_population")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.max_population)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.nb_promotions = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.nb_promotions.setObjectName("nb_promotions")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nb_promotions)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tol_evolutivite = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tol_evolutivite.setObjectName("tol_evolutivite")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tol_evolutivite)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.prob_stop = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.prob_stop.setObjectName("prob_stop")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prob_stop)
        self.ballot = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.ballot.setObjectName("ballot")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ballot)
        self.tol = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tol.setEnabled(False)
        self.tol.setObjectName("tol")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.tol)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_24.setEnabled(False)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.heuristics = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.heuristics.setObjectName("heuristics")
        self.verticalLayout.addWidget(self.heuristics)
        self.clear = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.clear.setBaseSize(QtCore.QSize(0, 10))
        self.clear.setObjectName("clear")
        self.verticalLayout.addWidget(self.clear)
        self.add_heuristics = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.add_heuristics.setObjectName("add_heuristics")
        self.verticalLayout.addWidget(self.add_heuristics)
        self.heuristics_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.heuristics_button.setObjectName("heuristics_button")
        self.verticalLayout.addWidget(self.heuristics_button)
        self.Parametres.addLayout(self.verticalLayout)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(230, 351, 102, 202))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.MidTools = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.MidTools.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MidTools.setContentsMargins(0, 0, 0, 0)
        self.MidTools.setSpacing(0)
        self.MidTools.setObjectName("MidTools")
        self.running = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.running.setMinimumSize(QtCore.QSize(100, 50))
        self.running.setObjectName("running")
        self.MidTools.addWidget(self.running)
        self.histogram = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.histogram.setMinimumSize(QtCore.QSize(100, 50))
        self.histogram.setObjectName("histogram")
        self.MidTools.addWidget(self.histogram)
        self.dataset = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.dataset.setMinimumSize(QtCore.QSize(100, 50))
        self.dataset.setObjectName("dataset")
        self.MidTools.addWidget(self.dataset)
        self.saving = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.saving.setMinimumSize(QtCore.QSize(100, 50))
        self.saving.setObjectName("saving")
        self.MidTools.addWidget(self.saving)
        self.Running = QtWidgets.QWidget(self.centralwidget)
        self.Running.setEnabled(True)
        self.Running.setGeometry(QtCore.QRect(330, 350, 631, 201))
        self.Running.setObjectName("Running")
        self.label_20 = QtWidgets.QLabel(self.Running)
        self.label_20.setGeometry(QtCore.QRect(560, 0, 61, 21))
        self.label_20.setTextFormat(QtCore.Qt.RichText)
        self.label_20.setObjectName("label_20")
        self.run = QtWidgets.QPushButton(self.Running)
        self.run.setGeometry(QtCore.QRect(250, 160, 121, 31))
        self.run.setObjectName("run")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Running)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 9, 136, 181))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.show_time = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.show_time.setMinimumSize(QtCore.QSize(0, 30))
        self.show_time.setObjectName("show_time")
        self.verticalLayout_2.addWidget(self.show_time)
        self.show_alpha_incarnation = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.show_alpha_incarnation.setMinimumSize(QtCore.QSize(0, 30))
        self.show_alpha_incarnation.setObjectName("show_alpha_incarnation")
        self.verticalLayout_2.addWidget(self.show_alpha_incarnation)
        self.show_tabou_list = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.show_tabou_list.setMinimumSize(QtCore.QSize(0, 30))
        self.show_tabou_list.setObjectName("show_tabou_list")
        self.verticalLayout_2.addWidget(self.show_tabou_list)
        self.show_animation = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.show_animation.setMinimumSize(QtCore.QSize(0, 30))
        self.show_animation.setObjectName("show_animation")
        self.verticalLayout_2.addWidget(self.show_animation)
        self.sequential_run = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.sequential_run.setMinimumSize(QtCore.QSize(0, 30))
        self.sequential_run.setObjectName("sequential_run")
        self.verticalLayout_2.addWidget(self.sequential_run)
        self.label_21 = QtWidgets.QLabel(self.Running)
        self.label_21.setGeometry(QtCore.QRect(300, 30, 47, 13))
        self.label_21.setObjectName("label_21")
        self.metrics = QtWidgets.QComboBox(self.Running)
        self.metrics.setGeometry(QtCore.QRect(240, 50, 141, 22))
        self.metrics.setObjectName("metrics")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.Running)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(240, 90, 146, 48))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.max_iteration = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.max_iteration.setObjectName("max_iteration")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.max_iteration)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.nb_cluster = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.nb_cluster.setObjectName("nb_cluster")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nb_cluster)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Running)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(480, 40, 136, 151))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.train_all = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.train_all.setMinimumSize(QtCore.QSize(0, 30))
        self.train_all.setObjectName("train_all")
        self.verticalLayout_3.addWidget(self.train_all)
        self.random_initalisation = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.random_initalisation.setMinimumSize(QtCore.QSize(0, 30))
        self.random_initalisation.setObjectName("random_initalisation")
        self.verticalLayout_3.addWidget(self.random_initalisation)
        self.only_global_crossing = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.only_global_crossing.setMinimumSize(QtCore.QSize(0, 30))
        self.only_global_crossing.setObjectName("only_global_crossing")
        self.verticalLayout_3.addWidget(self.only_global_crossing)
        self.evolve_strategies = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.evolve_strategies.setMinimumSize(QtCore.QSize(0, 30))
        self.evolve_strategies.setObjectName("evolve_strategies")
        self.verticalLayout_3.addWidget(self.evolve_strategies)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 180, 191, 51))
        self.widget.setObjectName("widget")
        self.bake = QtWidgets.QPushButton(self.centralwidget)
        self.bake.setGeometry(QtCore.QRect(520, 0, 121, 20))
        self.bake.setObjectName("bake")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HyperHeuristic"))
        self.label_10.setText(_translate("MainWindow", "                          Strategies"))
        self.label_12.setText(_translate("MainWindow", "Prob.M"))
        self.label_13.setText(_translate("MainWindow", "Prob.I"))
        self.label_14.setText(_translate("MainWindow", "Prob.O"))
        self.label_11.setText(_translate("MainWindow", "Prob.C"))
        self.add_strategy.setText(_translate("MainWindow", "Add Strategy"))
        self.label_15.setText(_translate("MainWindow", "                        Training model"))
        self.label_19.setText(_translate("MainWindow", "                         Tresholding type"))
        self.label_16.setText(_translate("MainWindow", "Nb.Iteration.treshold           "))
        self.label_2.setText(_translate("MainWindow", "  Prob.Supp "))
        self.label_3.setText(_translate("MainWindow", " Max.Attribute"))
        self.label_6.setText(_translate("MainWindow", " Max.Population"))
        self.label_7.setText(_translate("MainWindow", " Nb.Promotions"))
        self.label_8.setText(_translate("MainWindow", " Tol.Evolutivité"))
        self.label_9.setText(_translate("MainWindow", " Ballot"))
        self.label.setText(_translate("MainWindow", "  Prob.Stop  "))
        self.label_24.setText(_translate("MainWindow", "Tol"))
        self.label_4.setText(_translate("MainWindow", "                          Heurisitcs"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.heuristics_button.setText(_translate("MainWindow", "Add"))
        self.running.setText(_translate("MainWindow", "Runing          >"))
        self.histogram.setText(_translate("MainWindow", "Histogram     >"))
        self.dataset.setText(_translate("MainWindow", "Dataset      >"))
        self.saving.setText(_translate("MainWindow", "Saving      >"))
        self.label_20.setText(_translate("MainWindow", "Running"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.show_time.setText(_translate("MainWindow", "Show time"))
        self.show_alpha_incarnation.setText(_translate("MainWindow", "Show alpha incarnation"))
        self.show_tabou_list.setText(_translate("MainWindow", "Show tabou list"))
        self.show_animation.setText(_translate("MainWindow", "Show animation"))
        self.sequential_run.setText(_translate("MainWindow", "Sequential run"))
        self.label_21.setText(_translate("MainWindow", "Metrics"))
        self.label_22.setText(_translate("MainWindow", "Max.Iteration      "))
        self.label_23.setText(_translate("MainWindow", "Nb.Cluster"))
        self.train_all.setText(_translate("MainWindow", "Train all"))
        self.random_initalisation.setText(_translate("MainWindow", "Random initialisation"))
        self.only_global_crossing.setText(_translate("MainWindow", "Only global crossing"))
        self.evolve_strategies.setText(_translate("MainWindow", "Evolve strategies"))
        self.bake.setText(_translate("MainWindow", "Bake"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
